// ── components/SideBySide.jsx ───────────────────────────────
import React from "react";

/**
 * SideBySide
 * Places children in equal columns and forces images
 * to fill their grid cell width cleanly.
 */
export const SideBySide = ({
  children,
  gap = "1rem",
  maxWidth = "100%",
}) => {

  const containerStyle = {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap,
    maxWidth,
    margin: "0 auto",
    alignItems: "stretch",
  };

  const unwrapParagraph = child => {
    if (!React.isValidElement(child)) return child;

    // unwrap <p><img/></p> generated by Markdown
    if (child.type === "p") {
      const inner = React.Children.toArray(child.props.children).find(
        c => React.isValidElement(c) && c.type === "img"
      );
      return inner || child;
    }

    return child;
  };

  const cleanedChildren = React.Children.map(children, unwrapParagraph);

  return (
    <div style={containerStyle}>
      {cleanedChildren.map((child, index) => (
        <div key={index} style={{ width: "100%" }}>
          {React.cloneElement(child, {
            style: {
              width: "100%",
              height: "auto",
              display: "block",
              objectFit: "contain",
            }
          })}
        </div>
      ))}
    </div>
  );
};
